#!/usr/bin/env zsh

## zsh specific shell configs
## https://serverfault.com/questions/261802/what-are-the-functional-differences-between-profile-bash-profile-and-bashrc

if [ -r ~/.profile ]; then
    source ~/.profile
fi

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
if [ -r ~/.orbstack/shell/init.zsh ]; then
    source ~/.orbstack/shell/init.zsh
fi
