#!/usr/bin/env bash

## bash specific shell configs
## https://serverfault.com/questions/261802/what-are-the-functional-differences-between-profile-bash-profile-and-bashrc

if [ -r ~/.profile ]; then
    source ~/.profile
fi
if [ -r ./.bashrc ]; then
    source ~/.bashrc
fi

# Added by LM Studio CLI (lms)
if [ -d ~/.cache/lm-studio/bin ]; then
    export PATH="$PATH:~/.cache/lm-studio/bin"
fi
