#!/usr/bin/env bash

[ -x "/opt/homebrew/bin/brew" ] && eval $(/opt/homebrew/bin/brew shellenv)
[ -x "/usr/local/bin/brew" ] && eval $(/usr/local/bin/brew shellenv)
[ -x "/home/linuxbrew/.linuxbrew/bin/brew" ] && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

if command -v brew &> /dev/null; then

    # Groovy
    if [ -d $HOMEBREW_PREFIX/opt/groovy/libexec ]; then
        export GROOVY_HOME=$HOMEBREW_PREFIX/opt/groovy/libexec
    fi

fi
