#!/usr/bin/env bash

if [ $(uname) = "Darwin" ] ; then
    # Show/hide hidden files in Finder
    alias show="defaults write com.apple.Finder AppleShowAllFiles -bool true && killall Finder"
    alias hide="defaults write com.apple.Finder AppleShowAllFiles -bool false && killall Finder"
    alias myip="ipconfig getifaddr en0"
    alias icloud="brctl log --wait --shorten"

    # JDK
    if [ -x /usr/libexec/java_home ]
    then
        alias jdk8="export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)"
        alias jdk11="export JAVA_HOME=$(/usr/libexec/java_home -v 11)"
        alias jdk17="export JAVA_HOME=$(/usr/libexec/java_home -v 17)"
        alias jdk21="export JAVA_HOME=$(/usr/libexec/java_home -v 21)"
        alias jdk24="export JAVA_HOME=$(/usr/libexec/java_home -v 24)"
        alias mvn8="JAVA_HOME=$(/usr/libexec/java_home -v 1.8) mvn"
        alias mvn11="JAVA_HOME=$(/usr/libexec/java_home -v 11) mvn"
        alias mvn17="JAVA_HOME=$(/usr/libexec/java_home -v 17) mvn"
        alias mvn21="JAVA_HOME=$(/usr/libexec/java_home -v 21) mvn"
        alias mvn23="JAVA_HOME=$(/usr/libexec/java_home -v 23) mvn"
        alias mvnd8="JAVA_HOME=$(/usr/libexec/java_home -v 1.8) mvnd"
        alias mvnd11="JAVA_HOME=$(/usr/libexec/java_home -v 11) mvnd"
        alias mvnd17="JAVA_HOME=$(/usr/libexec/java_home -v 17) mvnd"
        alias mvnd21="JAVA_HOME=$(/usr/libexec/java_home -v 21) mvnd"
        alias mvnd24="JAVA_HOME=$(/usr/libexec/java_home -v 24) mvnd"
    fi

    export GRAALVM_HOME=$(find /Library/Java/JavaVirtualMachines -name "graalvm-21.jdk*")
    if [ -d $GRAALVM_HOME ]; then
        alias gjdk="export JAVA_HOME=$GRAALVM_HOME/Contents/Home"
        alias gmvn="JAVA_HOME=$GRAALVM_HOME/Contents/Home mvn"
        alias gmvnd="JAVA_HOME=$GRAALVM_HOME/Contents/Home mvnd"
    fi

    # IntelliJ IDEA > 2023.1
    if [ -d "/Applications/IntelliJ IDEA.app/Contents/MacOS" ]; then
        alias idea="open -na \"IntelliJ IDEA.app\" --args"
    elif [ -d "${HOME}/Applications/IntelliJ IDEA Ultimate.app" ]; then
        alias idea="open -na \"IntelliJ IDEA Ultimate.app\" --args"
    fi

    if [ -d "${HOME}/Applications/IntelliJ IDEA Community Edition.app" ]; then
        alias ideace="open -na \"IntelliJ IDEA Community Edition.app\" --args"
    fi

    if [ -d "${HOME}/Applications/IntelliJ IDEA Ultimate.app" ]; then
        alias ideaul="open -na \"IntelliJ IDEA Ultimate.app\" --args"
    fi

    # Virsh
    alias nucsh="virsh -c qemu+ssh://nuc01.rgielen.de/system?socket=/var/run/libvirt/libvirt-sock"

fi
