#!/usr/bin/env bash

export CURL_SSL_BACKEND="secure-transport"
ulimit -n 65536 -f unlimited

if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then 
    . $HOME/.nix-profile/etc/profile.d/nix.sh; 
fi

if command -v devbox &> /dev/null; then
    eval "$(devbox global shellenv --recompute)"
    source <(devbox completion $SHELL_TYPE)
fi

if command -v zoxide &> /dev/null; then
    eval "$(zoxide init ${SHELL_TYPE})"
fi
