#!/usr/bin/env bash

export CURL_SSL_BACKEND="secure-transport"
ulimit -n 65536 200000

if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then 
    . $HOME/.nix-profile/etc/profile.d/nix.sh; 
fi

if command -v devbox &> /dev/null; then
    eval "$(devbox global shellenv)"
    source <(devbox completion $SHELL_TYPE)
fi
